python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
python3 evo_Tum.py ~/dataset/Tum/folders
